"""Add GoogleSheetLead model for lead tracking

Revision ID: 2cb92cf50857
Revises: 66bc945b04de
Create Date: 2025-09-05 14:43:56.125006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb92cf50857'
down_revision: Union[str, Sequence[str], None] = '66bc945b04de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_googlesheet_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_row_id', sa.String(length=255), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IMPORTED', 'SKIPPED', 'ARCHIVED', 'ERROR', name='googlesheetlead_status_enum', native_enum=False), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_request_id'], ['shop_quoterequest.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_request_id')
    )
    op.create_index(op.f('ix_crm_googlesheet_lead_sheet_row_id'), 'crm_googlesheet_lead', ['sheet_row_id'], unique=True)
    op.create_index(op.f('ix_crm_googlesheet_lead_spreadsheet_id'), 'crm_googlesheet_lead', ['spreadsheet_id'], unique=False)
    op.create_index(op.f('ix_crm_googlesheet_lead_status'), 'crm_googlesheet_lead', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_googlesheet_lead_status'), table_name='crm_googlesheet_lead')
    op.drop_index(op.f('ix_crm_googlesheet_lead_spreadsheet_id'), table_name='crm_googlesheet_lead')
    op.drop_index(op.f('ix_crm_googlesheet_lead_sheet_row_id'), table_name='crm_googlesheet_lead')
    op.drop_table('crm_googlesheet_lead')
    # ### end Alembic commands ###