"""Change product descriptions to TEXT type

Revision ID: 3efeb482c524
Revises: 35d1621675ef
Create Date: 2025-09-02 15:44:22.260903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efeb482c524'
down_revision: Union[str, Sequence[str], None] = '35d1621675ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('shop_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('name_uz', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_uz', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_category_name_ru'), 'shop_category', ['name_ru'], unique=False)
    op.create_index(op.f('ix_shop_category_slug'), 'shop_category', ['slug'], unique=True)
    op.create_table('shop_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Имя клиента'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия клиента'),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Старые заметки'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('shop_contactnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['shop_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_contactnote_is_pinned'), 'shop_contactnote', ['is_pinned'], unique=False)
    op.create_table('shop_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=200), nullable=False),
    sa.Column('name_uz', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_description_ru', sa.Text(), nullable=True),
    sa.Column('short_description_uz', sa.Text(), nullable=True),
    sa.Column('full_description_ru', sa.Text(), nullable=True),
    sa.Column('full_description_uz', sa.Text(), nullable=True),
    sa.Column('main_image', sa.String(length=100), nullable=True),
    sa.Column('dimensions_ru', sa.Text(), nullable=True, comment='Размеры (RU)'),
    sa.Column('dimensions_uz', sa.Text(), nullable=True, comment="O'lchamlari (UZ)"),
    sa.Column('materials_ru', sa.Text(), nullable=True, comment='Материалы (RU), через новую строку'),
    sa.Column('materials_uz', sa.Text(), nullable=True, comment='Materiallar (UZ), через новую строку'),
    sa.Column('price_min', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='Цена за м2 от'),
    sa.Column('price_max', sa.DECIMAL(precision=12, scale=2), nullable=True, comment='Цена за м2 до'),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'PRE_ORDER', 'OUT_OF_STOCK', name='statusenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['shop_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_product_slug'), 'shop_product', ['slug'], unique=True)
    op.create_table('shop_registrationinvite',
    sa.Column('code', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(), nullable=True, comment='Заметка для кого это приглашение, например, email или имя'),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('shop_productimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('alt_text', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_quoterequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'completed', 'cancelled', name='statusenum', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('website', 'contact_form', name='sourceenum', native_enum=False), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('business_type', sa.String(length=255), nullable=True, comment='Тип бизнеса клиента'),
    sa.Column('dimensions', sa.String(length=255), nullable=True, comment='Размеры объекта'),
    sa.Column('investment_details', sa.Text(), nullable=True, comment='Бюджет/Инвестиции (Sarmoysi)'),
    sa.Column('conclusion', sa.Text(), nullable=True, comment='Заключение/Выводы (Xulosasi)'),
    sa.Column('additional_info', sa.Text(), nullable=True, comment='Дополнительные сведения'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['shop_contact.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_quoterequest_status'), 'shop_quoterequest', ['status'], unique=False)
    op.create_table('shop_statuschangelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('new', 'in_progress', 'completed', 'cancelled', name='statusenum', native_enum=False), nullable=False),
    sa.Column('new_status', sa.Enum('new', 'in_progress', 'completed', 'cancelled', name='statusenum', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['quote_request_id'], ['shop_quoterequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('quote_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['shop_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_request_id'], ['shop_quoterequest.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_task_completed'), 'shop_task', ['completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_task_completed'), table_name='shop_task')
    op.drop_table('shop_task')
    op.drop_table('shop_statuschangelog')
    op.drop_index(op.f('ix_shop_quoterequest_status'), table_name='shop_quoterequest')
    op.drop_table('shop_quoterequest')
    op.drop_table('shop_productimage')
    op.drop_table('shop_registrationinvite')
    op.drop_index(op.f('ix_shop_product_slug'), table_name='shop_product')
    op.drop_table('shop_product')
    op.drop_table('shop_notification')
    op.drop_index(op.f('ix_shop_contactnote_is_pinned'), table_name='shop_contactnote')
    op.drop_table('shop_contactnote')
    op.drop_table('shop_contact')
    op.drop_index(op.f('ix_shop_category_slug'), table_name='shop_category')
    op.drop_index(op.f('ix_shop_category_name_ru'), table_name='shop_category')
    op.drop_table('shop_category')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
