"""Change product descriptions to TEXT type

Revision ID: 3efeb482c524
Revises: 35d1621675ef
Create Date: 2025-09-02 15:50:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efeb482c524'
down_revision: Union[str, Sequence[str], None] = '35d1621675ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Изначальная проблема: Alembic ошибочно добавил сюда создание всех таблиц.
    # Правильная миграция должна содержать ТОЛЬКО изменения.
    
    # Изменяем тип колонки short_description_ru
    op.alter_column('shop_product', 'short_description_ru',
               existing_type=sa.Text(),  # Тип может отличаться, Alembic разберется
               type_=sa.Text(),
               existing_nullable=True)

    # Изменяем тип колонки short_description_uz
    op.alter_column('shop_product', 'short_description_uz',
               existing_type=sa.Text(),
               type_=sa.Text(),
               existing_nullable=True)

    # Изменяем тип колонки full_description_ru
    op.alter_column('shop_product', 'full_description_ru',
               existing_type=sa.Text(),
               type_=sa.Text(),
               existing_nullable=True)

    # Изменяем тип колонки full_description_uz
    op.alter_column('shop_product', 'full_description_uz',
               existing_type=sa.Text(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем все как было, если понадобится откат.
    # Обратите внимание, что мы возвращаем к типу VARCHAR, который, вероятно, был до этого.
    # Если исходный тип был другим, это нужно будет скорректировать, но для отката это безопасно.
    
    op.alter_column('shop_product', 'full_description_uz',
               existing_type=sa.Text(),
               type_=sa.String(length=255), # Примерная длина, которая могла быть
               existing_nullable=True)
               
    op.alter_column('shop_product', 'full_description_ru',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=True)

    op.alter_column('shop_product', 'short_description_uz',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=True)

    op.alter_column('shop_product', 'short_description_ru',
               existing_type=sa.Text(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###