"""Add subject column

Revision ID: 448babd7bc0c
Revises: e916445817de
Create Date: 2025-12-09 19:02:01.891772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448babd7bc0c'
down_revision: Union[str, Sequence[str], None] = 'e916445817de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название проекта'),
    sa.Column('quote_request_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=True),
    sa.Column('foreman_id', sa.Integer(), nullable=True),
    sa.Column('contract_amount', sa.DECIMAL(precision=15, scale=2), nullable=False, comment='Сумма контракта'),
    sa.Column('status', sa.Enum('DESIGN', 'PROCUREMENT', 'CONSTRUCTION', 'FINISHING', 'HANDOVER', 'COMPLETED', 'HOLD', name='project_status_enum', native_enum=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['foreman_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['quote_request_id'], ['shop_quoterequest.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_projectfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PHOTO_REPORT', 'DESIGN_DOC', 'DOCUMENT', name='file_type_enum', native_enum=False), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['shop_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transaction_type_enum', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Категория: Бетон, Аванс, Дизайн'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['shop_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shop_quoterequest', sa.Column('subject', sa.String(length=255), nullable=True, comment='Тема/причина обращения'))
    op.drop_constraint(op.f('shop_quoterequest_product_id_fkey'), 'shop_quoterequest', type_='foreignkey')
    op.drop_column('shop_quoterequest', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_quoterequest', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('shop_quoterequest_product_id_fkey'), 'shop_quoterequest', 'shop_product', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_column('shop_quoterequest', 'subject')
    op.drop_table('shop_transaction')
    op.drop_table('shop_projectfile')
    op.drop_table('shop_project')
    # ### end Alembic commands ###
