"""Add dimensions and materials to Product

Revision ID: 583ffc5705a5
Revises: 52955e1beab7
Create Date: 2025-08-12 13:21:34.993219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583ffc5705a5'
down_revision: Union[str, Sequence[str], None] = '52955e1beab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_product', sa.Column('dimensions_ru', sa.String(length=255), nullable=True, comment='Размеры (RU)'))
    op.add_column('shop_product', sa.Column('dimensions_uz', sa.String(length=255), nullable=True, comment="O'lchamlari (UZ)"))
    op.add_column('shop_product', sa.Column('materials_ru', sa.Text(), nullable=True, comment='Материалы (RU), через новую строку'))
    op.add_column('shop_product', sa.Column('materials_uz', sa.Text(), nullable=True, comment='Materiallar (UZ), через новую строку'))
    op.drop_column('shop_product', 'features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_product', sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('shop_product', 'materials_uz')
    op.drop_column('shop_product', 'materials_ru')
    op.drop_column('shop_product', 'dimensions_uz')
    op.drop_column('shop_product', 'dimensions_ru')
    # ### end Alembic commands ###
