# alembic/versions/66bc945b04de_....py

"""Update QuoteRequest StatusEnum to sales funnel stages

Revision ID: 66bc945b04de
Revises: 3efeb482c524
Create Date: 2025-09-04 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66bc945b04de'
down_revision: Union[str, None] = '3efeb482c524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Определяем старые и новые типы ENUM
old_status_enum = postgresql.ENUM('new', 'in_progress', 'completed', 'cancelled', name='statusenum')
new_status_enum = postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем временный тип ENUM, чтобы избежать конфликтов
    tmp_status_enum = postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum_new')
    tmp_status_enum.create(op.get_bind(), checkfirst=False)

    # Обновляем данные в таблице shop_quoterequest
    op.execute("""
        ALTER TABLE shop_quoterequest
        ALTER COLUMN status TYPE statusenum_new
        USING (CASE
            WHEN status = 'new' THEN 'imported'::statusenum_new
            WHEN status = 'in_progress' THEN 'qualification'::statusenum_new
            WHEN status = 'completed' THEN 'closed'::statusenum_new
            WHEN status = 'cancelled' THEN 'archived'::statusenum_new
            ELSE 'imported'::statusenum_new
        END)
    """)

    # Обновляем данные в таблице shop_statuschangelog для old_status
    op.execute("""
        ALTER TABLE shop_statuschangelog
        ALTER COLUMN old_status TYPE statusenum_new
        USING (CASE
            WHEN old_status = 'new' THEN 'imported'::statusenum_new
            WHEN old_status = 'in_progress' THEN 'qualification'::statusenum_new
            WHEN old_status = 'completed' THEN 'closed'::statusenum_new
            WHEN old_status = 'cancelled' THEN 'archived'::statusenum_new
            ELSE 'imported'::statusenum_new
        END)
    """)

    # Обновляем данные в таблице shop_statuschangelog для new_status
    op.execute("""
        ALTER TABLE shop_statuschangelog
        ALTER COLUMN new_status TYPE statusenum_new
        USING (CASE
            WHEN new_status = 'new' THEN 'imported'::statusenum_new
            WHEN new_status = 'in_progress' THEN 'qualification'::statusenum_new
            WHEN new_status = 'completed' THEN 'closed'::statusenum_new
            WHEN new_status = 'cancelled' THEN 'archived'::statusenum_new
            ELSE 'imported'::statusenum_new
        END)
    """)
    
    # Удаляем старый тип ENUM
    old_status_enum.drop(op.get_bind(), checkfirst=False)
    
    # Переименовываем новый тип в старое имя
    op.execute('ALTER TYPE statusenum_new RENAME TO statusenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Обратное преобразование сложнее, поэтому мы создадим новый тип и сконвертируем данные
    tmp_status_enum_old = postgresql.ENUM('new', 'in_progress', 'completed', 'cancelled', name='statusenum_old')
    tmp_status_enum_old.create(op.get_bind(), checkfirst=False)

    # Обновляем данные в таблице shop_quoterequest
    op.execute("""
        ALTER TABLE shop_quoterequest
        ALTER COLUMN status TYPE statusenum_old
        USING (CASE
            WHEN status = 'imported' THEN 'new'::statusenum_old
            WHEN status = 'qualification' THEN 'in_progress'::statusenum_old
            WHEN status = 'closed' THEN 'completed'::statusenum_old
            WHEN status = 'archived' THEN 'cancelled'::statusenum_old
            ELSE 'new'::statusenum_old
        END)
    """)

    # Обновляем данные в таблице shop_statuschangelog
    op.execute("""
        ALTER TABLE shop_statuschangelog
        ALTER COLUMN old_status TYPE statusenum_old
        USING (CASE
            WHEN old_status = 'imported' THEN 'new'::statusenum_old
            -- ... и так далее для других статусов
            ELSE 'new'::statusenum_old
        END)
    """)
    op.execute("""
        ALTER TABLE shop_statuschangelog
        ALTER COLUMN new_status TYPE statusenum_old
        USING (CASE
            WHEN new_status = 'imported' THEN 'new'::statusenum_old
            -- ... и так далее для других статусов
            ELSE 'new'::statusenum_old
        END)
    """)
    
    # Удаляем текущий тип ENUM
    new_status_enum.drop(op.get_bind(), checkfirst=False)
    
    # Переименовываем временный тип в основной
    op.execute('ALTER TYPE statusenum_old RENAME TO statusenum')
    # ### end Alembic commands ###