"""Update QuoteRequest StatusEnum to sales funnel stages

Revision ID: 66bc945b04de
Revises: 3efeb482c524
Create Date: 2025-09-04 11:48:15.372643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bc945b04de'
down_revision: Union[str, Sequence[str], None] = '3efeb482c524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_quoterequest', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'old_status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'new_status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_statuschangelog', 'new_status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'old_status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('shop_quoterequest', 'status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='statusenum', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
