"""fix_googlesheetlead_enum_handling

Revision ID: 94bd1a57fc9e
Revises: e3a34eb1ecdb
Create Date: 2025-09-13 12:19:54.426626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bd1a57fc9e'
down_revision: Union[str, Sequence[str], None] = 'e3a34eb1ecdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
