"""Add is_superuser flag to User model

Revision ID: a5bbfeeb7442
Revises: 2cb92cf50857
Create Date: 2025-09-06 10:27:21.330338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5bbfeeb7442'
down_revision: Union[str, Sequence[str], None] = '2cb92cf50857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем server_default, чтобы база знала, что ставить для существующих записей.
    op.add_column('auth_user', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'is_superuser')
    # ### end Alembic commands ###