"""Fix enums and expand contact field lengths

Revision ID: e3a34eb1ecdb
Revises: 2372266a737a
Create Date: 2025-09-11 17:01:33.836123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3a34eb1ecdb'
down_revision: Union[str, Sequence[str], None] = '2372266a737a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_contact', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_comment='Имя клиента',
               existing_nullable=False)
    op.alter_column('shop_contact', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_comment='Фамилия клиента',
               existing_nullable=True)
    op.alter_column('shop_contact', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('shop_product', 'status',
               existing_type=postgresql.ENUM('IN_STOCK', 'PRE_ORDER', 'OUT_OF_STOCK', name='statusenum'),
               type_=sa.Enum('IN_STOCK', 'PRE_ORDER', 'OUT_OF_STOCK', name='product_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('shop_quoterequest', 'status',
               existing_type=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'old_status',
               existing_type=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'new_status',
               existing_type=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               type_=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_statuschangelog', 'new_status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               type_=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               existing_nullable=False)
    op.alter_column('shop_statuschangelog', 'old_status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               type_=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               existing_nullable=False)
    op.alter_column('shop_quoterequest', 'status',
               existing_type=sa.Enum('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum', native_enum=False),
               type_=postgresql.ENUM('imported', 'qualification', 'contacted', 'proposal', 'negotiation', 'closed', 'archived', name='quoterequest_status_enum'),
               existing_nullable=False)
    op.alter_column('shop_product', 'status',
               existing_type=sa.Enum('IN_STOCK', 'PRE_ORDER', 'OUT_OF_STOCK', name='product_status_enum', native_enum=False),
               type_=postgresql.ENUM('IN_STOCK', 'PRE_ORDER', 'OUT_OF_STOCK', name='statusenum'),
               existing_nullable=False)
    op.alter_column('shop_contact', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('shop_contact', 'last_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_comment='Фамилия клиента',
               existing_nullable=True)
    op.alter_column('shop_contact', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_comment='Имя клиента',
               existing_nullable=False)
    # ### end Alembic commands ###
