"""add role to user model

Revision ID: efaa0334e565
Revises: 94bd1a57fc9e
Create Date: 2025-09-16 16:08:20.179395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaa0334e565'
down_revision: Union[str, Sequence[str], None] = '94bd1a57fc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('role', sa.Enum('manager', 'seo', 'admin', name='user_role_enum', native_enum=False), server_default='manager', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'role')
    # ### end Alembic commands ###
