user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    map $ssl_preread_server_name $backend_name {
        weconstruct.uz      upstream_site;
        www.weconstruct.uz  upstream_site;
        admin.weconstruct.uz upstream_admin;
        default             upstream_site;
    }

    upstream upstream_site {
        server site:8000;
    }
    upstream upstream_admin {
        server admin:8000;
    }

    server {
        listen 443;
        ssl_preread on;
        proxy_pass $backend_name;
    }
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /var/log/nginx/access.log;
    
    client_max_body_size 10M;

    server {
        listen 80;
        server_name weconstruct.uz www.weconstruct.uz admin.weconstruct.uz;
        return 301 https://$host$request_uri;
    }

    server {
        listen 8000 ssl http2;
        server_name weconstruct.uz www.weconstruct.uz admin.weconstruct.uz;

        ssl_certificate /etc/letsencrypt/live/weconstruct.uz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/weconstruct.uz/privkey.pem;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            if ($host ~* ^(www\.)?weconstruct\.uz$) {
                proxy_pass http://site:8000;
            }
            if ($host = 'admin.weconstruct.uz') {
                proxy_pass http://admin:8000;
            }
        }
        
        location /static/ {
            alias /app/src/static/;
            expires 30d;
        }

        location /media/ {
            alias /app/media/;
            expires 30d;
        }
    }
}